apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: services.inwinstack.com
spec:
  group: inwinstack.com
  version: v1
  names:
    kind: Service
    plural: services
    shortNames:
    - srvc
  scope: Cluster
  additionalPrinterColumns:
  - name: Status
    type: string
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: nats.inwinstack.com
spec:
  group: inwinstack.com
  version: v1
  names:
    kind: NAT
    plural: nats
  scope: Namespaced
  additionalPrinterColumns:
  - name: Status
    type: string
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: securities.inwinstack.com
spec:
  group: inwinstack.com
  version: v1
  names:
    kind: Security
    plural: securities
    shortNames:
    - sec
  scope: Namespaced
  additionalPrinterColumns:
  - name: Status
    type: string
    JSONPath: .status.phase
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp