apiVersion: v1
kind: Service
metadata:
  annotations:
    inwinstack.com/allow-security-policy: "false"
    inwinstack.com/allow-nat-policy: "false"
  labels:
    run: nginx
  name: nginx
  namespace: test
spec:
  externalIPs:
  - 172.29.188.2
  externalTrafficPolicy: Cluster
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: http-8080
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  sessionAffinity: None
  type: LoadBalancer