apiVersion: v1
kind: Service
metadata:
  annotations:
    inwinstack.com/allow-security-policy: "true"
    inwinstack.com/allow-nat-policy: "true"
  labels:
    run: nginx
  name: nginx
  namespace: test
spec:
  externalIPs:
  - 172.22.132.192
  ports:
  - name: http-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: ClusterIP